# Generated by Django 4.1.7 on 2023-03-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_review_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='book',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
